AddUIforStrings
boonandmoil/localiser-web pull request #2
Opened 2023-09-12 11:11 UTC by D-Antonelli

2023-09-27 14:48 UTC, henryallsuch requested changes
Nice work! It's a great start, just a few changes.

2023-09-27 14:48 UTC, henryallsuch commented on src/requests/translations/index.ts
> +  const url = `http://localhost:3001/v1/strings/${stringId}/update`;
Can this API url be from an environment variable?

2023-09-27 14:48 UTC, henryallsuch commented on src/requests/translations/index.ts
> +  const url = "http://localhost:3001/v1/strings/import";
Can this API url be from an environment variable? Same here (maybe just the host & port)

2023-09-27 14:48 UTC, henryallsuch commented on src/components/languageDropdown.tsx
> +      console.log(error.message);
Could we show a message at this point?

2023-09-27 14:48 UTC, henryallsuch commented on src/components/localizeForm.tsx
> +      console.log(error.message);
Could we show just a simple error message? Maybe a generic one for now.

2023-09-28 13:30 UTC, D-Antonelli commented on src/requests/translations/index.ts
> +  const url = "http://localhost:3001/v1/strings/import";
👍🏽

2023-09-28 15:37 UTC, henryallsuch approved these changes
👍  nice work

2023-10-11 13:48 UTC, merged